// Code generated by qtc from "route.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/route.qtpl:2
package templates

//line templates/route.qtpl:2
import (
	"github.com/NULLx76/bird-lg-go/pkg/proxy"
	"github.com/valyala/fasthttp"
)

//line templates/route.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/route.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/route.qtpl:9
type RoutePage struct {
	CTX  *fasthttp.RequestCtx
	Peer *proxy.RouteDetails
}

//line templates/route.qtpl:15
func (p *RoutePage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/route.qtpl:15
	qw422016.N().S(`
	Bird Looking Glass -
`)
//line templates/route.qtpl:17
}

//line templates/route.qtpl:17
func (p *RoutePage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/route.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/route.qtpl:17
	p.StreamTitle(qw422016)
//line templates/route.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line templates/route.qtpl:17
}

//line templates/route.qtpl:17
func (p *RoutePage) Title() string {
//line templates/route.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/route.qtpl:17
	p.WriteTitle(qb422016)
//line templates/route.qtpl:17
	qs422016 := string(qb422016.B)
//line templates/route.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/route.qtpl:17
	return qs422016
//line templates/route.qtpl:17
}

//line templates/route.qtpl:19
func (p *RoutePage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/route.qtpl:19
	qw422016.N().S(`

`)
//line templates/route.qtpl:21
}

//line templates/route.qtpl:21
func (p *RoutePage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/route.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/route.qtpl:21
	p.StreamBody(qw422016)
//line templates/route.qtpl:21
	qt422016.ReleaseWriter(qw422016)
//line templates/route.qtpl:21
}

//line templates/route.qtpl:21
func (p *RoutePage) Body() string {
//line templates/route.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/route.qtpl:21
	p.WriteBody(qb422016)
//line templates/route.qtpl:21
	qs422016 := string(qb422016.B)
//line templates/route.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/route.qtpl:21
	return qs422016
//line templates/route.qtpl:21
}
