kind: ConfigMap
apiVersion: v1
metadata:
  name: bird-lg-api-configmap
data:
  config.yaml: |
    listen: ":8000"
    servers:
      xirion: "http://192.168.0.127:8000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bird-lg-api
  labels:
    app: bird-lg-api
    keel.sh/policy: force
    app.kubernetes.io/part-of: bird-lg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bird-lg-api
  template:
    metadata:
      labels:
        app: bird-lg-api
        app.kubernetes.io/part-of: bird-lg
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: bird-lg-api-configmap
      containers:
        - name: bird-lg-api
          image: harbor.xirion.net/library/bird-lg/api
          env:
            - name: CONFIG_FILE
              value: "/app/config.yaml"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: bird-lg-api-service
  labels:
    app.kubernetes.io/part-of: bird-lg
spec:
  selector:
    app: bird-lg-api
  ports:
    - protocol: TCP
      port: 8000
