apiVersion: apps/v1
kind: Deployment
metadata:
  name: bird-lg-api
  labels:
    app: bird-lg-api
    keel.sh/policy: force
    app.kubernetes.io/part-of: bird-lg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bird-lg-api
  template:
    metadata:
      labels:
        app: bird-lg-api
        app.kubernetes.io/part-of: bird-lg
    spec:
      containers:
      - name: bird-lg-api
        image: harbor.xirion.net/library/bird-lg/api
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: bird-lg-api-service
  labels:
    app.kubernetes.io/part-of: bird-lg
spec:
  selector:
    app: bird-lg-api
  ports:
    - protocol: TCP
      port: 8000
