apiVersion: apps/v1
kind: Deployment
metadata:
  name: bird-lg-frontend
  labels:
    app: bird-lg-frontend
    keel.sh/policy: force
    app.kubernetes.io/part-of: bird-lg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bird-lg-frontend
  template:
    metadata:
      labels:
        app: bird-lg-frontend
        app.kubernetes.io/part-of: bird-lg
    spec:
      containers:
      - name: bird-lg-frontend
        image: harbor.xirion.net/library/bird-lg/frontend
        env:
          - name: API_URL
            value: "http://bird-lg-api-service:8000"
          - name: ADDRESS
            value: ":8080"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bird-lg-frontend-service
  labels:
    app.kubernetes.io/part-of: bird-lg
spec:
  selector:
    app: bird-lg-frontend
  ports:
    - protocol: TCP
      port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bird-lg-frontend-ingress
  labels:
    app.kubernetes.io/part-of: bird-lg
spec:
  ingressClassName: "traefik"
  rules:
  - host: "lg.xirion.net"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bird-lg-frontend-service
            port:
              number: 8080
