// Code generated by qtc from "homepage.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/homepage.qtpl:1
package templates

//line templates/homepage.qtpl:1
import "github.com/valyala/fasthttp"

//line templates/homepage.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/homepage.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/homepage.qtpl:4
type MainPage struct {
	CTX *fasthttp.RequestCtx
}

//line templates/homepage.qtpl:10
func (p *MainPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/homepage.qtpl:10
	qw422016.N().S(`
	This is the main page
`)
//line templates/homepage.qtpl:12
}

//line templates/homepage.qtpl:12
func (p *MainPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/homepage.qtpl:12
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/homepage.qtpl:12
	p.StreamTitle(qw422016)
//line templates/homepage.qtpl:12
	qt422016.ReleaseWriter(qw422016)
//line templates/homepage.qtpl:12
}

//line templates/homepage.qtpl:12
func (p *MainPage) Title() string {
//line templates/homepage.qtpl:12
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/homepage.qtpl:12
	p.WriteTitle(qb422016)
//line templates/homepage.qtpl:12
	qs422016 := string(qb422016.B)
//line templates/homepage.qtpl:12
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/homepage.qtpl:12
	return qs422016
//line templates/homepage.qtpl:12
}

//line templates/homepage.qtpl:15
func (p *MainPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/homepage.qtpl:15
	qw422016.N().S(`
	<h1>Main page</h1>
	<div>
		Stuff here!
	</div>
	<div>
		Some info about you:<br/>
		IP: <b>`)
//line templates/homepage.qtpl:22
	qw422016.E().S(p.CTX.RemoteIP().String())
//line templates/homepage.qtpl:22
	qw422016.N().S(`</b><br/>
		User-Agent: <b>`)
//line templates/homepage.qtpl:23
	qw422016.E().Z(p.CTX.UserAgent())
//line templates/homepage.qtpl:23
	qw422016.N().S(`</b><br/>
	</div>
`)
//line templates/homepage.qtpl:25
}

//line templates/homepage.qtpl:25
func (p *MainPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/homepage.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/homepage.qtpl:25
	p.StreamBody(qw422016)
//line templates/homepage.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line templates/homepage.qtpl:25
}

//line templates/homepage.qtpl:25
func (p *MainPage) Body() string {
//line templates/homepage.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/homepage.qtpl:25
	p.WriteBody(qb422016)
//line templates/homepage.qtpl:25
	qs422016 := string(qb422016.B)
//line templates/homepage.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/homepage.qtpl:25
	return qs422016
//line templates/homepage.qtpl:25
}
