// Code generated by qtc from "homepage.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/homepage.qtpl:2
package templates

//line templates/homepage.qtpl:2
import (
	"github.com/NULLx76/bird-lg-go/api/proxy"
	"github.com/valyala/fasthttp"
)

//line templates/homepage.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/homepage.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/homepage.qtpl:9
type MainPage struct {
	CTX       *fasthttp.RequestCtx
	Summaries map[string]proxy.SummaryTable
}

//line templates/homepage.qtpl:16
func (p *MainPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/homepage.qtpl:16
	qw422016.N().S(`
	This is the main page
`)
//line templates/homepage.qtpl:18
}

//line templates/homepage.qtpl:18
func (p *MainPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/homepage.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/homepage.qtpl:18
	p.StreamTitle(qw422016)
//line templates/homepage.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line templates/homepage.qtpl:18
}

//line templates/homepage.qtpl:18
func (p *MainPage) Title() string {
//line templates/homepage.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/homepage.qtpl:18
	p.WriteTitle(qb422016)
//line templates/homepage.qtpl:18
	qs422016 := string(qb422016.B)
//line templates/homepage.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/homepage.qtpl:18
	return qs422016
//line templates/homepage.qtpl:18
}

//line templates/homepage.qtpl:21
func (p *MainPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/homepage.qtpl:21
	qw422016.N().S(`
	<h1>dn42 Looking Glass</h1>
    `)
//line templates/homepage.qtpl:23
	for name, server := range p.Summaries {
//line templates/homepage.qtpl:23
		qw422016.N().S(`
    <div class="text-center">
        <h2 class="p-3">Server: `)
//line templates/homepage.qtpl:25
		qw422016.E().S(name)
//line templates/homepage.qtpl:25
		qw422016.N().S(`</h2>
        <table>
            <tr>
                <th>Name</th>
                <th>Proto</th>
                <th>Table</th>
                <th>State</th>
                <th>Since</th>
                <th>Info</th>
            </tr>
            `)
//line templates/homepage.qtpl:35
		for row := range server {
//line templates/homepage.qtpl:35
			qw422016.N().S(`
            <tr>
                <td>`)
//line templates/homepage.qtpl:37
			qw422016.E().S(server[row].Name)
//line templates/homepage.qtpl:37
			qw422016.N().S(`</td>
                <td>`)
//line templates/homepage.qtpl:38
			qw422016.E().S(server[row].Proto)
//line templates/homepage.qtpl:38
			qw422016.N().S(`</td>
                <td>`)
//line templates/homepage.qtpl:39
			qw422016.E().S(server[row].Table)
//line templates/homepage.qtpl:39
			qw422016.N().S(`</td>
                <td>`)
//line templates/homepage.qtpl:40
			qw422016.E().S(server[row].State)
//line templates/homepage.qtpl:40
			qw422016.N().S(`</td>
                <td>`)
//line templates/homepage.qtpl:41
			qw422016.E().S(server[row].Since)
//line templates/homepage.qtpl:41
			qw422016.N().S(`</td>
                <td>`)
//line templates/homepage.qtpl:42
			qw422016.E().S(server[row].Info)
//line templates/homepage.qtpl:42
			qw422016.N().S(`</td>
            </tr>
            `)
//line templates/homepage.qtpl:44
		}
//line templates/homepage.qtpl:44
		qw422016.N().S(`
        </table>
    </div>
    `)
//line templates/homepage.qtpl:47
	}
//line templates/homepage.qtpl:47
	qw422016.N().S(`
`)
//line templates/homepage.qtpl:48
}

//line templates/homepage.qtpl:48
func (p *MainPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/homepage.qtpl:48
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/homepage.qtpl:48
	p.StreamBody(qw422016)
//line templates/homepage.qtpl:48
	qt422016.ReleaseWriter(qw422016)
//line templates/homepage.qtpl:48
}

//line templates/homepage.qtpl:48
func (p *MainPage) Body() string {
//line templates/homepage.qtpl:48
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/homepage.qtpl:48
	p.WriteBody(qb422016)
//line templates/homepage.qtpl:48
	qs422016 := string(qb422016.B)
//line templates/homepage.qtpl:48
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/homepage.qtpl:48
	return qs422016
//line templates/homepage.qtpl:48
}
