name: Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Frontend Docker image
      run: make docker_build_frontend
    - name: API Docker image
      run: make docker_build_api
